<!--
 * @Author: 吴楚标
 * @Date: 2021-05-11 21:34:26
 * @LastEditors: 吴楚标
 * @LastEditTime: 2021-05-11 21:38:18
 * @Description: 
-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>
        //promise对象失败的回调

        const p = new Promise((resolve,reject)=>{
            setTimeout(()=>{
                //设置 p 的状态为失败 并设置失败的值
                reject('出错啦');
            },1000)
        })

        // p.then(value=>{},reason=>{
        //     console.error(reason);
        // })

        p.catch(reason=>{
            console.warn(reason);
        })
    </script>
</head>
<body>
    
</body>
</html>